# Generated by Django 4.0.4 on 2022-04-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schnupperanmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('program', models.CharField(choices=[('BA', 'Bachelor Cognitive Science'), ('MA', 'Master Cognitive Science')], max_length=2)),
                ('accomodation', models.BooleanField()),
                ('food', models.CharField(blank=True, choices=[('VE', 'vegan'), ('VT', 'vegetarian'), ('OV', 'omnivore')], max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('validation_id', models.UUIDField(editable=False)),
                ('validated', models.BooleanField(default=False, editable=False)),
                ('mkdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
