# Generated by Django 4.0.4 on 2022-05-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogscinet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verein',
            name='iban',
        ),
        migrations.AddField(
            model_name='verein',
            name='privacy',
            field=models.BooleanField(default=False, verbose_name='I agree to the data privacy declaration as given below'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verein',
            name='membership',
            field=models.CharField(choices=[('A', 'I am a member of F2IKW and want to stay a member.'), ('N', "I want to become a member now and I'll be able to join the hybrid meeting on July, 16th, 16:00"), ('L', 'I plan to become a member later (selected plan is not binding, but we will remember you)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='verein',
            name='suggested_name',
            field=models.CharField(max_length=128, verbose_name='Suggested name for the association (examples suggested so far: "Coxi Club" or "CogSci Network"'),
        ),
    ]
