# Generated by Django 4.0.4 on 2022-05-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogscinet', '0002_remove_verein_iban_verein_privacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verein',
            name='membership',
            field=models.CharField(choices=[('A', 'I am a member of F2IKW and want to stay a member.'), ('N', "I want to become a member now and I'll be able to join the hybrid meeting on July, 16th, 16:00"), ('L', 'I plan to become a member later (selected plan is not binding, but we will remind you)')], max_length=1),
        ),
    ]
