# Generated by Django 4.0.4 on 2022-05-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogscinet', '0003_alter_verein_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verein',
            name='membership',
            field=models.CharField(choices=[('A', 'I am a member of F2IKW and want to stay a member.'), ('N', "I want to become a member now and I'll be able to join the hybrid meeting on July, 13th, 18:00"), ('L', 'I plan to become a member later (selected plan is not binding, but we will remind you)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='verein',
            name='plan',
            field=models.CharField(choices=[('R', 'Reduced (21€)'), ('N', 'Regular (42€)'), ('S', 'Senior (84€)'), ('I', 'Company, silver member (420€)'), ('G', 'Company, gold member (42 * 42€ = 1.764€)'), ('L', 'Individual amount > 84€ for individuals, > 1764€ for companys, given below)')], max_length=1),
        ),
    ]
