# Generated by Django 4.0.4 on 2022-05-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogscinet', '0005_verein_company_alter_verein_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verein',
            name='company',
            field=models.CharField(blank=True, max_length=128, verbose_name='Company name (if registering as a company member)'),
        ),
        migrations.AlterField(
            model_name='verein',
            name='extra_fee',
            field=models.IntegerField(blank=True, verbose_name='Optional: Higher membership fee per year'),
        ),
    ]
