# Generated by Django 4.0.4 on 2022-05-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogscinet', '0006_alter_verein_company_alter_verein_extra_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verein',
            name='extra_fee',
            field=models.IntegerField(blank=True, null=True, verbose_name='Optional: Higher membership fee per year'),
        ),
    ]
